export const declarationIntro =
  "I declare that the information given is correct and I agree to abide by the rules and regulation of the Medical Institute. We have received full information as herein below:";

export const declarationPoints = [
  "I am taking admission to the medical college through Dr. Rasal's Sunder education consultancy.",
  "I have completed all formalities required by Medical Council Of India and will be responsible to have Eligibility Certificate from Medical Council of India (MCI).",
  "We are aware the Screening Test to qualify for Practice in India after this doctorate degree by National Medical Commission.",
  "While taking admission, we have verified the entire information of the university ourselves, accordingly if there is any change in the government rules in the future, it will be acceptable, we will not blame anyone in any way.",
  "We are also aware that said University is listed in the World Health Organization (WHO).",
  "We have checked all the approvals of the university regarding the university ourselves.",
  "We are known and agreed all education, examination practices of this country according to itself country law.",
  "We are aware and introduced the education fees, other allied expenses, food accommodation, hostel fees, transportation and other Visa extension what so ever there of. All provision of above said expenses are borne by us/my family members.",
  "Hostel and mess is compulsory for the first year.",
  "We are also aware the intimation that, in case of any other reason what so ever caused to cancel the Admission, the Processing fees will NOT be REFUND in any Condition.",
  "We are ready to pay consultancy fee to Dr. Rasal's Sunder education consultancy and we will not ask for Refund in any case.",
  "In case the Visa we get for the target country, and if we do not satisfy the educational system of it, and or if we face any physical, atmospheric, homesickness problem, otherwise financial problem occurred, the student may come return to his/her country but against first year full fees will be payable. All this intimation is given to concerned student before they processed for admission procedure.",
  "The student is bounded to follow all rule & regulation of the University & sunder educational consultants.",
  "We are here by submitting our Processing fees to Sunder Education Consultant and requested to proceed further procedure.",
  "If there is any natural or unnatural harm to life treating in the future, it will be our own responsibility and Dr. Rasal's consultancy will have no connection with it.",
  "The relationship between Dr. Rasal and his consultancy will be limited only until our admission is confirmed.",
  "Dr. Rasal's Sunder Education Consultant Nasik has given us complete information while taking admission abroad and has explained to us that it is mandatory to pay the college fee before going abroad, and we will not have any complaints about it.",
  "We are fully aware and agree that we will not have any kind of monetary or exchange relationship with Dr. Rasal other than 75000/-.",
  "The amount once paid will only be refunded if and only if MBBSDIRECT failed to provide the admission to the university for which student has applied.",
  "If admission is canceled because of late payment, students will not be eligible for a refund.",
  "If a student voluntarily terminates their admission process, they will not be eligible for a refund.",
  "We will not blame Sunder Education Consultant and Dr. Rasal for any change in the rules by the Government of India in the future, they will be acceptable to us.",
  "If we have any complaint about Dr. Rasal in the future, we will file a complaint in the police station under the jurisdiction of Sunder Education Consultant office.",
  "In case of any judicial matter then all the dispute will be subject to Nasik Court only.",
  "We are agreed with all above said terms and conditions.",
  "I have read the terms and conditions, so I am applying for University. I am giving my consent to Dr. Rasal's Sunder education consultancy to initiate my admission process on my behalf.",
];
